# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kivi_pb2 as kivi__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kivi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KiviStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/kivi.v1.Kivi/Append',
                request_serializer=kivi__pb2.AppendRequest.SerializeToString,
                response_deserializer=kivi__pb2.Receipt.FromString,
                _registered_method=True)
        self.AppendBatch = channel.stream_unary(
                '/kivi.v1.Kivi/AppendBatch',
                request_serializer=kivi__pb2.AppendRequest.SerializeToString,
                response_deserializer=kivi__pb2.ReceiptList.FromString,
                _registered_method=True)
        self.AppendPrivate = channel.unary_unary(
                '/kivi.v1.Kivi/AppendPrivate',
                request_serializer=kivi__pb2.AppendRequest.SerializeToString,
                response_deserializer=kivi__pb2.Receipt.FromString,
                _registered_method=True)
        self.Erase = channel.unary_unary(
                '/kivi.v1.Kivi/Erase',
                request_serializer=kivi__pb2.EraseRequest.SerializeToString,
                response_deserializer=kivi__pb2.Receipt.FromString,
                _registered_method=True)
        self.GetRecord = channel.unary_unary(
                '/kivi.v1.Kivi/GetRecord',
                request_serializer=kivi__pb2.GetRecordRequest.SerializeToString,
                response_deserializer=kivi__pb2.RecordReply.FromString,
                _registered_method=True)
        self.Replay = channel.unary_stream(
                '/kivi.v1.Kivi/Replay',
                request_serializer=kivi__pb2.ReplayRequest.SerializeToString,
                response_deserializer=kivi__pb2.RecordReply.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/kivi.v1.Kivi/Verify',
                request_serializer=kivi__pb2.Empty.SerializeToString,
                response_deserializer=kivi__pb2.VerifyReport.FromString,
                _registered_method=True)
        self.QueryTable = channel.unary_unary(
                '/kivi.v1.Kivi/QueryTable',
                request_serializer=kivi__pb2.TableRequest.SerializeToString,
                response_deserializer=kivi__pb2.TracedAnswer.FromString,
                _registered_method=True)
        self.QuerySubject = channel.unary_unary(
                '/kivi.v1.Kivi/QuerySubject',
                request_serializer=kivi__pb2.SubjectRequest.SerializeToString,
                response_deserializer=kivi__pb2.TracedAnswer.FromString,
                _registered_method=True)
        self.QueryGraph = channel.unary_unary(
                '/kivi.v1.Kivi/QueryGraph',
                request_serializer=kivi__pb2.Empty.SerializeToString,
                response_deserializer=kivi__pb2.ViewState.FromString,
                _registered_method=True)
        self.QuerySeries = channel.unary_unary(
                '/kivi.v1.Kivi/QuerySeries',
                request_serializer=kivi__pb2.SeriesRequest.SerializeToString,
                response_deserializer=kivi__pb2.ViewState.FromString,
                _registered_method=True)
        self.Why = channel.unary_unary(
                '/kivi.v1.Kivi/Why',
                request_serializer=kivi__pb2.WhyRequest.SerializeToString,
                response_deserializer=kivi__pb2.RecordList.FromString,
                _registered_method=True)
        self.Audit = channel.unary_unary(
                '/kivi.v1.Kivi/Audit',
                request_serializer=kivi__pb2.AuditRequest.SerializeToString,
                response_deserializer=kivi__pb2.AuditFinding.FromString,
                _registered_method=True)
        self.Seal = channel.unary_unary(
                '/kivi.v1.Kivi/Seal',
                request_serializer=kivi__pb2.Empty.SerializeToString,
                response_deserializer=kivi__pb2.Receipt.FromString,
                _registered_method=True)
        self.Rotate = channel.unary_unary(
                '/kivi.v1.Kivi/Rotate',
                request_serializer=kivi__pb2.Empty.SerializeToString,
                response_deserializer=kivi__pb2.RotateInfo.FromString,
                _registered_method=True)
        self.Backup = channel.unary_stream(
                '/kivi.v1.Kivi/Backup',
                request_serializer=kivi__pb2.BackupRequest.SerializeToString,
                response_deserializer=kivi__pb2.BackupChunk.FromString,
                _registered_method=True)
        self.Attest = channel.unary_unary(
                '/kivi.v1.Kivi/Attest',
                request_serializer=kivi__pb2.Empty.SerializeToString,
                response_deserializer=kivi__pb2.Attestation.FromString,
                _registered_method=True)
        self.Vote = channel.unary_unary(
                '/kivi.v1.Kivi/Vote',
                request_serializer=kivi__pb2.VoteRequest.SerializeToString,
                response_deserializer=kivi__pb2.VoteReply.FromString,
                _registered_method=True)
        self.Beat = channel.unary_unary(
                '/kivi.v1.Kivi/Beat',
                request_serializer=kivi__pb2.BeatRequest.SerializeToString,
                response_deserializer=kivi__pb2.BeatReply.FromString,
                _registered_method=True)
        self.Replicate = channel.stream_stream(
                '/kivi.v1.Kivi/Replicate',
                request_serializer=kivi__pb2.ReplicateAck.SerializeToString,
                response_deserializer=kivi__pb2.RecordReply.FromString,
                _registered_method=True)
        self.Witness = channel.unary_unary(
                '/kivi.v1.Kivi/Witness',
                request_serializer=kivi__pb2.WitnessRequest.SerializeToString,
                response_deserializer=kivi__pb2.Receipt.FromString,
                _registered_method=True)
        self.Similar = channel.unary_unary(
                '/kivi.v1.Kivi/Similar',
                request_serializer=kivi__pb2.SimilarRequest.SerializeToString,
                response_deserializer=kivi__pb2.SimilarReply.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/kivi.v1.Kivi/Login',
                request_serializer=kivi__pb2.LoginRequest.SerializeToString,
                response_deserializer=kivi__pb2.LoginReply.FromString,
                _registered_method=True)
        self.Head = channel.unary_unary(
                '/kivi.v1.Kivi/Head',
                request_serializer=kivi__pb2.Empty.SerializeToString,
                response_deserializer=kivi__pb2.HeadReply.FromString,
                _registered_method=True)
        self.QueryViewPage = channel.unary_unary(
                '/kivi.v1.Kivi/QueryViewPage',
                request_serializer=kivi__pb2.ViewPageRequest.SerializeToString,
                response_deserializer=kivi__pb2.ViewPage.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/kivi.v1.Kivi/Subscribe',
                request_serializer=kivi__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=kivi__pb2.RecordReply.FromString,
                _registered_method=True)
        self.GraphNeighbors = channel.unary_unary(
                '/kivi.v1.Kivi/GraphNeighbors',
                request_serializer=kivi__pb2.GraphNeighborsRequest.SerializeToString,
                response_deserializer=kivi__pb2.GraphEdges.FromString,
                _registered_method=True)
        self.GraphReachable = channel.unary_unary(
                '/kivi.v1.Kivi/GraphReachable',
                request_serializer=kivi__pb2.GraphReachableRequest.SerializeToString,
                response_deserializer=kivi__pb2.GraphReachableReply.FromString,
                _registered_method=True)
        self.GraphPath = channel.unary_unary(
                '/kivi.v1.Kivi/GraphPath',
                request_serializer=kivi__pb2.GraphPathRequest.SerializeToString,
                response_deserializer=kivi__pb2.GraphPathReply.FromString,
                _registered_method=True)


class KiviServicer:
    """Missing associated documentation comment in .proto file."""

    def Append(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendBatch(self, request_iterator, context):
        """client-streaming bulk load
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendPrivate(self, request, context):
        """encrypted body (crypto-erase later)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Erase(self, request, context):
        """destroy the key, file the erasure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replay(self, request, context):
        """server-streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySubject(self, request, context):
        """QuerySubject (G15): TableRequest's whole-row sibling. QueryTable answers
        one (subject, attribute) cell; a caller that doesn't already know which
        attributes exist for a subject had no way to ask "what do we know about
        X?" without paging the whole table (QueryViewPage) hunting for one key.
        Same traced contract, same view (Table) and cache tiers underneath —
        this is a new EXTRACTION over an index that already existed, not a new
        index: the value_json is the whole row {attribute: value, ...} and the
        trace is the union of every event that established any cell in it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySeries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Why(self, request, context):
        """the receipts themselves
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Audit(self, request, context):
        """recompile-and-compare
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Seal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rotate(self, request, context):
        """close the period (F6)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Backup(self, request, context):
        """hot consistent backup (G6)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attest(self, request, context):
        """portable signed claim (G4)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Vote(self, request, context):
        """Cluster plane (G8, PLAN4): Raft-style election + quorum-acked replication.
        Only meaningful when KIVI_CLUSTER is set; single-node servers answer
        FailedPrecondition.
        election ballot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Beat(self, request, context):
        """leader heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replicate(self, request_iterator, context):
        """The follower opens the stream to the LEADER: the leader pushes records,
        the follower sends acks on the same stream. Acks drive the commit index.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Witness(self, request, context):
        """Federation (PLAN6): fetch a fresh attestation from a peer and FILE it in
        this ledger as a kivi.witness event — mutual testimony without consensus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Similar(self, request, context):
        """Semantic view (PLAN7): traced similarity search. Every hit is a record
        number with its score and raw record; the reply names the model and the
        covered scope — an untraced score does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Identity plane (PLAN8): password login → session token (Bearer). User
        management itself is receipted kivi.user events (admin plane / local CLI).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Head(self, request, context):
        """Head is the cheap orientation call: the ledger's last record number and
        head hash, straight from the open writer — NO cryptographic audit runs.
        Tail readers (recent_events, pagination) should use this, and reach for
        Verify only when integrity itself is the question.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryViewPage(self, request, context):
        """Paged view reads: deterministic KEYSET pagination over a compiled view's
        canonical (sorted) keys — no offsets, no drift. Snapshot pinning: page 1
        answers with the scope it folded to; pass that scope back as as_of on
        later pages and EVERY page describes the same moment (time travel reused
        as pagination glue). Record streams page differently: Replay(from) — the
        record number IS the cursor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe (G14): a TYPE-FILTERED live feed for point consumers that only
        care about one or two event types (a worker fed only kivi.apikey, a
        dashboard fed only kivi.metric) — the same live-tail mechanism as Replay,
        but the server drops non-matching records before they cross the wire
        instead of making every consumer receive and discard everything.

        Honesty note: filtering BY DESIGN creates gaps in the record numbering,
        so this stream does NOT carry Replay's gapless/chain-adjacency promise —
        each delivered record's OWN hash (and seal signature, for kivi.seal
        records) is still independently verifiable, proving "byte-exact what the
        ledger holds," but never "you received everything." A consumer that
        needs the stronger, audit-grade guarantee (replicas, backup, CDC that
        must prove no record was skipped) uses Replay — unfiltered — instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GraphNeighbors(self, request, context):
        """Graph traversal over `relation` events (traced, bounded, as-of). The server
        folds relations into an adjacency and walks it; every answer carries the
        record numbers of the edges it crossed. Reader role.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GraphReachable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GraphPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KiviServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=kivi__pb2.AppendRequest.FromString,
                    response_serializer=kivi__pb2.Receipt.SerializeToString,
            ),
            'AppendBatch': grpc.stream_unary_rpc_method_handler(
                    servicer.AppendBatch,
                    request_deserializer=kivi__pb2.AppendRequest.FromString,
                    response_serializer=kivi__pb2.ReceiptList.SerializeToString,
            ),
            'AppendPrivate': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendPrivate,
                    request_deserializer=kivi__pb2.AppendRequest.FromString,
                    response_serializer=kivi__pb2.Receipt.SerializeToString,
            ),
            'Erase': grpc.unary_unary_rpc_method_handler(
                    servicer.Erase,
                    request_deserializer=kivi__pb2.EraseRequest.FromString,
                    response_serializer=kivi__pb2.Receipt.SerializeToString,
            ),
            'GetRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecord,
                    request_deserializer=kivi__pb2.GetRecordRequest.FromString,
                    response_serializer=kivi__pb2.RecordReply.SerializeToString,
            ),
            'Replay': grpc.unary_stream_rpc_method_handler(
                    servicer.Replay,
                    request_deserializer=kivi__pb2.ReplayRequest.FromString,
                    response_serializer=kivi__pb2.RecordReply.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=kivi__pb2.Empty.FromString,
                    response_serializer=kivi__pb2.VerifyReport.SerializeToString,
            ),
            'QueryTable': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTable,
                    request_deserializer=kivi__pb2.TableRequest.FromString,
                    response_serializer=kivi__pb2.TracedAnswer.SerializeToString,
            ),
            'QuerySubject': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySubject,
                    request_deserializer=kivi__pb2.SubjectRequest.FromString,
                    response_serializer=kivi__pb2.TracedAnswer.SerializeToString,
            ),
            'QueryGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryGraph,
                    request_deserializer=kivi__pb2.Empty.FromString,
                    response_serializer=kivi__pb2.ViewState.SerializeToString,
            ),
            'QuerySeries': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySeries,
                    request_deserializer=kivi__pb2.SeriesRequest.FromString,
                    response_serializer=kivi__pb2.ViewState.SerializeToString,
            ),
            'Why': grpc.unary_unary_rpc_method_handler(
                    servicer.Why,
                    request_deserializer=kivi__pb2.WhyRequest.FromString,
                    response_serializer=kivi__pb2.RecordList.SerializeToString,
            ),
            'Audit': grpc.unary_unary_rpc_method_handler(
                    servicer.Audit,
                    request_deserializer=kivi__pb2.AuditRequest.FromString,
                    response_serializer=kivi__pb2.AuditFinding.SerializeToString,
            ),
            'Seal': grpc.unary_unary_rpc_method_handler(
                    servicer.Seal,
                    request_deserializer=kivi__pb2.Empty.FromString,
                    response_serializer=kivi__pb2.Receipt.SerializeToString,
            ),
            'Rotate': grpc.unary_unary_rpc_method_handler(
                    servicer.Rotate,
                    request_deserializer=kivi__pb2.Empty.FromString,
                    response_serializer=kivi__pb2.RotateInfo.SerializeToString,
            ),
            'Backup': grpc.unary_stream_rpc_method_handler(
                    servicer.Backup,
                    request_deserializer=kivi__pb2.BackupRequest.FromString,
                    response_serializer=kivi__pb2.BackupChunk.SerializeToString,
            ),
            'Attest': grpc.unary_unary_rpc_method_handler(
                    servicer.Attest,
                    request_deserializer=kivi__pb2.Empty.FromString,
                    response_serializer=kivi__pb2.Attestation.SerializeToString,
            ),
            'Vote': grpc.unary_unary_rpc_method_handler(
                    servicer.Vote,
                    request_deserializer=kivi__pb2.VoteRequest.FromString,
                    response_serializer=kivi__pb2.VoteReply.SerializeToString,
            ),
            'Beat': grpc.unary_unary_rpc_method_handler(
                    servicer.Beat,
                    request_deserializer=kivi__pb2.BeatRequest.FromString,
                    response_serializer=kivi__pb2.BeatReply.SerializeToString,
            ),
            'Replicate': grpc.stream_stream_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=kivi__pb2.ReplicateAck.FromString,
                    response_serializer=kivi__pb2.RecordReply.SerializeToString,
            ),
            'Witness': grpc.unary_unary_rpc_method_handler(
                    servicer.Witness,
                    request_deserializer=kivi__pb2.WitnessRequest.FromString,
                    response_serializer=kivi__pb2.Receipt.SerializeToString,
            ),
            'Similar': grpc.unary_unary_rpc_method_handler(
                    servicer.Similar,
                    request_deserializer=kivi__pb2.SimilarRequest.FromString,
                    response_serializer=kivi__pb2.SimilarReply.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=kivi__pb2.LoginRequest.FromString,
                    response_serializer=kivi__pb2.LoginReply.SerializeToString,
            ),
            'Head': grpc.unary_unary_rpc_method_handler(
                    servicer.Head,
                    request_deserializer=kivi__pb2.Empty.FromString,
                    response_serializer=kivi__pb2.HeadReply.SerializeToString,
            ),
            'QueryViewPage': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryViewPage,
                    request_deserializer=kivi__pb2.ViewPageRequest.FromString,
                    response_serializer=kivi__pb2.ViewPage.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=kivi__pb2.SubscribeRequest.FromString,
                    response_serializer=kivi__pb2.RecordReply.SerializeToString,
            ),
            'GraphNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GraphNeighbors,
                    request_deserializer=kivi__pb2.GraphNeighborsRequest.FromString,
                    response_serializer=kivi__pb2.GraphEdges.SerializeToString,
            ),
            'GraphReachable': grpc.unary_unary_rpc_method_handler(
                    servicer.GraphReachable,
                    request_deserializer=kivi__pb2.GraphReachableRequest.FromString,
                    response_serializer=kivi__pb2.GraphReachableReply.SerializeToString,
            ),
            'GraphPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GraphPath,
                    request_deserializer=kivi__pb2.GraphPathRequest.FromString,
                    response_serializer=kivi__pb2.GraphPathReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kivi.v1.Kivi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kivi.v1.Kivi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Kivi:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Append',
            kivi__pb2.AppendRequest.SerializeToString,
            kivi__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kivi.v1.Kivi/AppendBatch',
            kivi__pb2.AppendRequest.SerializeToString,
            kivi__pb2.ReceiptList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendPrivate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/AppendPrivate',
            kivi__pb2.AppendRequest.SerializeToString,
            kivi__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Erase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Erase',
            kivi__pb2.EraseRequest.SerializeToString,
            kivi__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/GetRecord',
            kivi__pb2.GetRecordRequest.SerializeToString,
            kivi__pb2.RecordReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kivi.v1.Kivi/Replay',
            kivi__pb2.ReplayRequest.SerializeToString,
            kivi__pb2.RecordReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Verify',
            kivi__pb2.Empty.SerializeToString,
            kivi__pb2.VerifyReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/QueryTable',
            kivi__pb2.TableRequest.SerializeToString,
            kivi__pb2.TracedAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySubject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/QuerySubject',
            kivi__pb2.SubjectRequest.SerializeToString,
            kivi__pb2.TracedAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/QueryGraph',
            kivi__pb2.Empty.SerializeToString,
            kivi__pb2.ViewState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/QuerySeries',
            kivi__pb2.SeriesRequest.SerializeToString,
            kivi__pb2.ViewState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Why(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Why',
            kivi__pb2.WhyRequest.SerializeToString,
            kivi__pb2.RecordList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Audit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Audit',
            kivi__pb2.AuditRequest.SerializeToString,
            kivi__pb2.AuditFinding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Seal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Seal',
            kivi__pb2.Empty.SerializeToString,
            kivi__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rotate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Rotate',
            kivi__pb2.Empty.SerializeToString,
            kivi__pb2.RotateInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Backup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kivi.v1.Kivi/Backup',
            kivi__pb2.BackupRequest.SerializeToString,
            kivi__pb2.BackupChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Attest',
            kivi__pb2.Empty.SerializeToString,
            kivi__pb2.Attestation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Vote',
            kivi__pb2.VoteRequest.SerializeToString,
            kivi__pb2.VoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Beat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Beat',
            kivi__pb2.BeatRequest.SerializeToString,
            kivi__pb2.BeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replicate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kivi.v1.Kivi/Replicate',
            kivi__pb2.ReplicateAck.SerializeToString,
            kivi__pb2.RecordReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Witness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Witness',
            kivi__pb2.WitnessRequest.SerializeToString,
            kivi__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Similar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Similar',
            kivi__pb2.SimilarRequest.SerializeToString,
            kivi__pb2.SimilarReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Login',
            kivi__pb2.LoginRequest.SerializeToString,
            kivi__pb2.LoginReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Head(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/Head',
            kivi__pb2.Empty.SerializeToString,
            kivi__pb2.HeadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryViewPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/QueryViewPage',
            kivi__pb2.ViewPageRequest.SerializeToString,
            kivi__pb2.ViewPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kivi.v1.Kivi/Subscribe',
            kivi__pb2.SubscribeRequest.SerializeToString,
            kivi__pb2.RecordReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GraphNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/GraphNeighbors',
            kivi__pb2.GraphNeighborsRequest.SerializeToString,
            kivi__pb2.GraphEdges.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GraphReachable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/GraphReachable',
            kivi__pb2.GraphReachableRequest.SerializeToString,
            kivi__pb2.GraphReachableReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GraphPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kivi.v1.Kivi/GraphPath',
            kivi__pb2.GraphPathRequest.SerializeToString,
            kivi__pb2.GraphPathReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
