// kivi gRPC contract, v1 — THE single source of truth for the data plane
// (PLAN2 F3). Freezing rule: a published field number is never changed or
// reused; additions only.
//
// Bodies, records and view states travel as CANONICAL JSON STRINGS, not as
// protobuf structs: format v1 is JSON-native and google.protobuf.Struct would
// lose int64 fidelity (its numbers are doubles). The JSON string preserves the
// exact bytes the ledger reasons about.
//
// Honesty note: proto3 cannot mark fields required — the "no answer without a
// trace" guarantee (trace/scope always present) is enforced by the server test
// suite instead.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/kivi.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A directed, traced relation edge: source —relation→ target, set by record no.
type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      string                 `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	No            int64                  `protobuf:"varint,3,opt,name=no,proto3" json:"no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_api_kivi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{0}
}

func (x *GraphEdge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GraphEdge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GraphEdge) GetNo() int64 {
	if x != nil {
		return x.No
	}
	return 0
}

type GraphNeighborsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	AsOf          *int64                 `protobuf:"varint,2,opt,name=as_of,json=asOf,proto3,oneof" json:"as_of,omitempty"` // pin to the graph as of a record number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNeighborsRequest) Reset() {
	*x = GraphNeighborsRequest{}
	mi := &file_api_kivi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNeighborsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNeighborsRequest) ProtoMessage() {}

func (x *GraphNeighborsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNeighborsRequest.ProtoReflect.Descriptor instead.
func (*GraphNeighborsRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{1}
}

func (x *GraphNeighborsRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *GraphNeighborsRequest) GetAsOf() int64 {
	if x != nil && x.AsOf != nil {
		return *x.AsOf
	}
	return 0
}

type GraphEdges struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*GraphEdge           `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"` // the relation scan hit its cap — a partial graph
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdges) Reset() {
	*x = GraphEdges{}
	mi := &file_api_kivi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdges) ProtoMessage() {}

func (x *GraphEdges) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdges.ProtoReflect.Descriptor instead.
func (*GraphEdges) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{2}
}

func (x *GraphEdges) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *GraphEdges) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type GraphReachableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Depth         int64                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"` // max hops (0 → 3)
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // max nodes returned (0 → default)
	AsOf          *int64                 `protobuf:"varint,4,opt,name=as_of,json=asOf,proto3,oneof" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphReachableRequest) Reset() {
	*x = GraphReachableRequest{}
	mi := &file_api_kivi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphReachableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphReachableRequest) ProtoMessage() {}

func (x *GraphReachableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphReachableRequest.ProtoReflect.Descriptor instead.
func (*GraphReachableRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{3}
}

func (x *GraphReachableRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *GraphReachableRequest) GetDepth() int64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *GraphReachableRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GraphReachableRequest) GetAsOf() int64 {
	if x != nil && x.AsOf != nil {
		return *x.AsOf
	}
	return 0
}

// One node reached by a traversal, with the edge record numbers along the
// shortest discovering path (its proof).
type GraphReached struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Depth         int64                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	Trace         []int64                `protobuf:"varint,3,rep,packed,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphReached) Reset() {
	*x = GraphReached{}
	mi := &file_api_kivi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphReached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphReached) ProtoMessage() {}

func (x *GraphReached) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphReached.ProtoReflect.Descriptor instead.
func (*GraphReached) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{4}
}

func (x *GraphReached) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *GraphReached) GetDepth() int64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *GraphReached) GetTrace() []int64 {
	if x != nil {
		return x.Trace
	}
	return nil
}

type GraphReachableReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphReached        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphReachableReply) Reset() {
	*x = GraphReachableReply{}
	mi := &file_api_kivi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphReachableReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphReachableReply) ProtoMessage() {}

func (x *GraphReachableReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphReachableReply.ProtoReflect.Descriptor instead.
func (*GraphReachableReply) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{5}
}

func (x *GraphReachableReply) GetNodes() []*GraphReached {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphReachableReply) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type GraphPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Depth         int64                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"` // max hops (0 → 6)
	AsOf          *int64                 `protobuf:"varint,4,opt,name=as_of,json=asOf,proto3,oneof" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphPathRequest) Reset() {
	*x = GraphPathRequest{}
	mi := &file_api_kivi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphPathRequest) ProtoMessage() {}

func (x *GraphPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphPathRequest.ProtoReflect.Descriptor instead.
func (*GraphPathRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{6}
}

func (x *GraphPathRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GraphPathRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GraphPathRequest) GetDepth() int64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *GraphPathRequest) GetAsOf() int64 {
	if x != nil && x.AsOf != nil {
		return *x.AsOf
	}
	return 0
}

// One step of a path: from —relation→ to, via edge record no.
type GraphHop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	No            int64                  `protobuf:"varint,4,opt,name=no,proto3" json:"no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphHop) Reset() {
	*x = GraphHop{}
	mi := &file_api_kivi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphHop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphHop) ProtoMessage() {}

func (x *GraphHop) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphHop.ProtoReflect.Descriptor instead.
func (*GraphHop) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{7}
}

func (x *GraphHop) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GraphHop) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GraphHop) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GraphHop) GetNo() int64 {
	if x != nil {
		return x.No
	}
	return 0
}

type GraphPathReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hops          []*GraphHop            `protobuf:"bytes,1,rep,name=hops,proto3" json:"hops,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphPathReply) Reset() {
	*x = GraphPathReply{}
	mi := &file_api_kivi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphPathReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphPathReply) ProtoMessage() {}

func (x *GraphPathReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphPathReply.ProtoReflect.Descriptor instead.
func (*GraphPathReply) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{8}
}

func (x *GraphPathReply) GetHops() []*GraphHop {
	if x != nil {
		return x.Hops
	}
	return nil
}

func (x *GraphPathReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GraphPathReply) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`     // start record number (the consumer's cursor)
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"` // keep the stream open, push new matching records
	Types         []string               `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`    // empty = every type (no filtering, still gap-unsafe by contract)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_kivi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SubscribeRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *SubscribeRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type ViewPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`                         // table | graph | series
	AfterKey      string                 `protobuf:"bytes,2,opt,name=after_key,json=afterKey,proto3" json:"after_key,omitempty"` // keyset cursor: keys strictly after this ("" = start)
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                      // max entries (0 → 100; capped at 1000)
	AsOf          *int64                 `protobuf:"varint,4,opt,name=as_of,json=asOf,proto3,oneof" json:"as_of,omitempty"`      // pin to a snapshot (use page 1's scope)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewPageRequest) Reset() {
	*x = ViewPageRequest{}
	mi := &file_api_kivi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewPageRequest) ProtoMessage() {}

func (x *ViewPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewPageRequest.ProtoReflect.Descriptor instead.
func (*ViewPageRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{10}
}

func (x *ViewPageRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *ViewPageRequest) GetAfterKey() string {
	if x != nil {
		return x.AfterKey
	}
	return ""
}

func (x *ViewPageRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ViewPageRequest) GetAsOf() int64 {
	if x != nil && x.AsOf != nil {
		return *x.AsOf
	}
	return 0
}

type ViewEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                              // table: subject · graph: edge · series: series name
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"` // canonical JSON of that entry (row / edge / points)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewEntry) Reset() {
	*x = ViewEntry{}
	mi := &file_api_kivi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewEntry) ProtoMessage() {}

func (x *ViewEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewEntry.ProtoReflect.Descriptor instead.
func (*ViewEntry) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{11}
}

func (x *ViewEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ViewEntry) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

type ViewPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ViewEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextKey       string                 `protobuf:"bytes,2,opt,name=next_key,json=nextKey,proto3" json:"next_key,omitempty"` // "" = no more pages
	Scope         int64                  `protobuf:"varint,3,opt,name=scope,proto3" json:"scope,omitempty"`                   // pass back as as_of to keep paging THIS snapshot
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`                      // digest of the WHOLE view state at that scope
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewPage) Reset() {
	*x = ViewPage{}
	mi := &file_api_kivi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewPage) ProtoMessage() {}

func (x *ViewPage) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewPage.ProtoReflect.Descriptor instead.
func (*ViewPage) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{12}
}

func (x *ViewPage) GetEntries() []*ViewEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ViewPage) GetNextKey() string {
	if x != nil {
		return x.NextKey
	}
	return ""
}

func (x *ViewPage) GetScope() int64 {
	if x != nil {
		return x.Scope
	}
	return 0
}

func (x *ViewPage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type HeadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeadNo        int64                  `protobuf:"varint,1,opt,name=head_no,json=headNo,proto3" json:"head_no,omitempty"`      // last record number (-1 = empty ledger)
	HeadHash      string                 `protobuf:"bytes,2,opt,name=head_hash,json=headHash,proto3" json:"head_hash,omitempty"` // hash of that record ("" = empty ledger)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadReply) Reset() {
	*x = HeadReply{}
	mi := &file_api_kivi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadReply) ProtoMessage() {}

func (x *HeadReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadReply.ProtoReflect.Descriptor instead.
func (*HeadReply) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{13}
}

func (x *HeadReply) GetHeadNo() int64 {
	if x != nil {
		return x.HeadNo
	}
	return 0
}

func (x *HeadReply) GetHeadHash() string {
	if x != nil {
		return x.HeadHash
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_kivi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{14}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // session bearer token
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`   // reader | writer | admin
	ExpiresUnix   int64                  `protobuf:"varint,3,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_kivi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{15}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LoginReply) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

type SimilarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	K             int64                  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"` // 0 → 5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarRequest) Reset() {
	*x = SimilarRequest{}
	mi := &file_api_kivi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarRequest) ProtoMessage() {}

func (x *SimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarRequest.ProtoReflect.Descriptor instead.
func (*SimilarRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{16}
}

func (x *SimilarRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SimilarRequest) GetK() int64 {
	if x != nil {
		return x.K
	}
	return 0
}

type SimilarHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	No            int64                  `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	RecordJson    string                 `protobuf:"bytes,3,opt,name=record_json,json=recordJson,proto3" json:"record_json,omitempty"` // the receipt itself, canonical
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarHit) Reset() {
	*x = SimilarHit{}
	mi := &file_api_kivi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarHit) ProtoMessage() {}

func (x *SimilarHit) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarHit.ProtoReflect.Descriptor instead.
func (*SimilarHit) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{17}
}

func (x *SimilarHit) GetNo() int64 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *SimilarHit) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SimilarHit) GetRecordJson() string {
	if x != nil {
		return x.RecordJson
	}
	return ""
}

type SimilarReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SimilarHit          `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	Scope         int64                  `protobuf:"varint,2,opt,name=scope,proto3" json:"scope,omitempty"` // history covered by the index at answer time
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`  // which ruler measured the similarity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarReply) Reset() {
	*x = SimilarReply{}
	mi := &file_api_kivi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarReply) ProtoMessage() {}

func (x *SimilarReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarReply.ProtoReflect.Descriptor instead.
func (*SimilarReply) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{18}
}

func (x *SimilarReply) GetHits() []*SimilarHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SimilarReply) GetScope() int64 {
	if x != nil {
		return x.Scope
	}
	return 0
}

func (x *SimilarReply) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Candidate     string                 `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`                // candidate's cluster node name (addr)
	LastTerm      int64                  `protobuf:"varint,3,opt,name=last_term,json=lastTerm,proto3" json:"last_term,omitempty"` // term of the newest kivi.takeover record
	LastNo        int64                  `protobuf:"varint,4,opt,name=last_no,json=lastNo,proto3" json:"last_no,omitempty"`       // head record number (-1 = empty)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_api_kivi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{19}
}

func (x *VoteRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteRequest) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *VoteRequest) GetLastTerm() int64 {
	if x != nil {
		return x.LastTerm
	}
	return 0
}

func (x *VoteRequest) GetLastNo() int64 {
	if x != nil {
		return x.LastNo
	}
	return 0
}

type VoteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Granted       bool                   `protobuf:"varint,2,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteReply) Reset() {
	*x = VoteReply{}
	mi := &file_api_kivi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteReply) ProtoMessage() {}

func (x *VoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteReply.ProtoReflect.Descriptor instead.
func (*VoteReply) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{20}
}

func (x *VoteReply) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteReply) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

type BeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Leader        string                 `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	CommitNo      int64                  `protobuf:"varint,3,opt,name=commit_no,json=commitNo,proto3" json:"commit_no,omitempty"` // leader's quorum-acked head (followers may expose it)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeatRequest) Reset() {
	*x = BeatRequest{}
	mi := &file_api_kivi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatRequest) ProtoMessage() {}

func (x *BeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatRequest.ProtoReflect.Descriptor instead.
func (*BeatRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{21}
}

func (x *BeatRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *BeatRequest) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *BeatRequest) GetCommitNo() int64 {
	if x != nil {
		return x.CommitNo
	}
	return 0
}

type BeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeatReply) Reset() {
	*x = BeatReply{}
	mi := &file_api_kivi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatReply) ProtoMessage() {}

func (x *BeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatReply.ProtoReflect.Descriptor instead.
func (*BeatReply) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{22}
}

func (x *BeatReply) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type ReplicateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follower      string                 `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"` // sender's cluster node name (first message identifies)
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	AckedNo       int64                  `protobuf:"varint,3,opt,name=acked_no,json=ackedNo,proto3" json:"acked_no,omitempty"` // highest record durably applied (fsynced) locally
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateAck) Reset() {
	*x = ReplicateAck{}
	mi := &file_api_kivi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateAck) ProtoMessage() {}

func (x *ReplicateAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateAck.ProtoReflect.Descriptor instead.
func (*ReplicateAck) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{23}
}

func (x *ReplicateAck) GetFollower() string {
	if x != nil {
		return x.Follower
	}
	return ""
}

func (x *ReplicateAck) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ReplicateAck) GetAckedNo() int64 {
	if x != nil {
		return x.AckedNo
	}
	return 0
}

type WitnessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"` // peer address to attest (must be on the witness list)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WitnessRequest) Reset() {
	*x = WitnessRequest{}
	mi := &file_api_kivi_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WitnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessRequest) ProtoMessage() {}

func (x *WitnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessRequest.ProtoReflect.Descriptor instead.
func (*WitnessRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{24}
}

func (x *WitnessRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

// Attestation is federation candidate C's first stone: a FRESH seal, exported
// as a portable, self-contained, independently verifiable claim — "my ledger's
// history up to record N has head H; here is my signature." A peer verifies it
// offline (canonical hash + Ed25519 over seal_json) and may file it in its own
// ledger as testimony. No merging, no trust by assertion — receipts only.
type Attestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pk            string                 `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`                                 // signer public key (hex) — also embedded in the seal
	SealNo        int64                  `protobuf:"varint,2,opt,name=seal_no,json=sealNo,proto3" json:"seal_no,omitempty"`          // the seal record's number
	CoveredNo     int64                  `protobuf:"varint,3,opt,name=covered_no,json=coveredNo,proto3" json:"covered_no,omitempty"` // last record covered by this attestation
	HeadHash      string                 `protobuf:"bytes,4,opt,name=head_hash,json=headHash,proto3" json:"head_hash,omitempty"`     // the seal record's hash (the chain head)
	SealJson      string                 `protobuf:"bytes,5,opt,name=seal_json,json=sealJson,proto3" json:"seal_json,omitempty"`     // the full seal record, canonical JSON — the proof itself
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_api_kivi_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{25}
}

func (x *Attestation) GetPk() string {
	if x != nil {
		return x.Pk
	}
	return ""
}

func (x *Attestation) GetSealNo() int64 {
	if x != nil {
		return x.SealNo
	}
	return 0
}

func (x *Attestation) GetCoveredNo() int64 {
	if x != nil {
		return x.CoveredNo
	}
	return 0
}

func (x *Attestation) GetHeadHash() string {
	if x != nil {
		return x.HeadHash
	}
	return ""
}

func (x *Attestation) GetSealJson() string {
	if x != nil {
		return x.SealJson
	}
	return ""
}

type BackupRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Password string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"` // optional envelope encryption (empty = plaintext)
	// Incremental mode (G7): stream only records AFTER the anchor. The anchor
	// must name both the number and the hash of the last record the caller
	// already holds — a mismatched anchor is refused (take a full backup).
	Incremental   bool   `protobuf:"varint,2,opt,name=incremental,proto3" json:"incremental,omitempty"`
	SinceNo       int64  `protobuf:"varint,3,opt,name=since_no,json=sinceNo,proto3" json:"since_no,omitempty"`
	SinceHash     string `protobuf:"bytes,4,opt,name=since_hash,json=sinceHash,proto3" json:"since_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_api_kivi_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{26}
}

func (x *BackupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BackupRequest) GetIncremental() bool {
	if x != nil {
		return x.Incremental
	}
	return false
}

func (x *BackupRequest) GetSinceNo() int64 {
	if x != nil {
		return x.SinceNo
	}
	return 0
}

func (x *BackupRequest) GetSinceHash() string {
	if x != nil {
		return x.SinceHash
	}
	return ""
}

type BackupChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupChunk) Reset() {
	*x = BackupChunk{}
	mi := &file_api_kivi_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChunk) ProtoMessage() {}

func (x *BackupChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChunk.ProtoReflect.Descriptor instead.
func (*BackupChunk) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{27}
}

func (x *BackupChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RotateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        int64                  `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`                                   // 1-based period number that was archived
	Archive       string                 `protobuf:"bytes,2,opt,name=archive,proto3" json:"archive,omitempty"`                                  // archive file name
	ArchiveSha256 string                 `protobuf:"bytes,3,opt,name=archive_sha256,json=archiveSha256,proto3" json:"archive_sha256,omitempty"` // whole-file fingerprint bound into the rotation receipt
	FirstNo       int64                  `protobuf:"varint,4,opt,name=first_no,json=firstNo,proto3" json:"first_no,omitempty"`                  // first record number of the new period
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateInfo) Reset() {
	*x = RotateInfo{}
	mi := &file_api_kivi_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateInfo) ProtoMessage() {}

func (x *RotateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateInfo.ProtoReflect.Descriptor instead.
func (*RotateInfo) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{28}
}

func (x *RotateInfo) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *RotateInfo) GetArchive() string {
	if x != nil {
		return x.Archive
	}
	return ""
}

func (x *RotateInfo) GetArchiveSha256() string {
	if x != nil {
		return x.ArchiveSha256
	}
	return ""
}

func (x *RotateInfo) GetFirstNo() int64 {
	if x != nil {
		return x.FirstNo
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_kivi_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{29}
}

type AppendRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                         // event type ("kivi.*" is reserved and refused)
	BodyJson string                 `protobuf:"bytes,2,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"` // the event body as JSON
	Purpose  string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`                   // v3: legal basis for processing (KVKK/GDPR); validated
	// against the purpose registry. actor is NOT here — the
	// server stamps it from the authenticated identity.
	Schema        int64 `protobuf:"varint,4,opt,name=schema,proto3" json:"schema,omitempty"` // v3: body-shape version for this type (0 = unversioned);
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_api_kivi_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{30}
}

func (x *AppendRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AppendRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

func (x *AppendRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *AppendRequest) GetSchema() int64 {
	if x != nil {
		return x.Schema
	}
	return 0
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	No            int64                  `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_api_kivi_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{31}
}

func (x *Receipt) GetNo() int64 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *Receipt) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Receipt) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ReceiptList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipts      []*Receipt             `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptList) Reset() {
	*x = ReceiptList{}
	mi := &file_api_kivi_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptList) ProtoMessage() {}

func (x *ReceiptList) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptList.ProtoReflect.Descriptor instead.
func (*ReceiptList) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{32}
}

func (x *ReceiptList) GetReceipts() []*Receipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

type EraseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	No            int64                  `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // required: even forgetting leaves a trace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EraseRequest) Reset() {
	*x = EraseRequest{}
	mi := &file_api_kivi_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EraseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseRequest) ProtoMessage() {}

func (x *EraseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseRequest.ProtoReflect.Descriptor instead.
func (*EraseRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{33}
}

func (x *EraseRequest) GetNo() int64 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *EraseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	No            int64                  `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	Unseal        bool                   `protobuf:"varint,2,opt,name=unseal,proto3" json:"unseal,omitempty"` // open a private body if the key still exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_api_kivi_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{34}
}

func (x *GetRecordRequest) GetNo() int64 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *GetRecordRequest) GetUnseal() bool {
	if x != nil {
		return x.Unseal
	}
	return false
}

type RecordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordJson    string                 `protobuf:"bytes,1,opt,name=record_json,json=recordJson,proto3" json:"record_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordReply) Reset() {
	*x = RecordReply{}
	mi := &file_api_kivi_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordReply) ProtoMessage() {}

func (x *RecordReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordReply.ProtoReflect.Descriptor instead.
func (*RecordReply) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{35}
}

func (x *RecordReply) GetRecordJson() string {
	if x != nil {
		return x.RecordJson
	}
	return ""
}

type ReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"` // keep the stream open and push new records as they land
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_api_kivi_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{36}
}

func (x *ReplayRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ReplayRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type VerifyReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Records       int64                  `protobuf:"varint,2,opt,name=records,proto3" json:"records,omitempty"`
	Seals         int64                  `protobuf:"varint,3,opt,name=seals,proto3" json:"seals,omitempty"`
	UnsealedTail  int64                  `protobuf:"varint,4,opt,name=unsealed_tail,json=unsealedTail,proto3" json:"unsealed_tail,omitempty"`
	TornTail      bool                   `protobuf:"varint,5,opt,name=torn_tail,json=tornTail,proto3" json:"torn_tail,omitempty"`
	HasDefect     bool                   `protobuf:"varint,6,opt,name=has_defect,json=hasDefect,proto3" json:"has_defect,omitempty"`
	DefectNo      int64                  `protobuf:"varint,7,opt,name=defect_no,json=defectNo,proto3" json:"defect_no,omitempty"`
	DefectReason  string                 `protobuf:"bytes,8,opt,name=defect_reason,json=defectReason,proto3" json:"defect_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyReport) Reset() {
	*x = VerifyReport{}
	mi := &file_api_kivi_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyReport) ProtoMessage() {}

func (x *VerifyReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyReport.ProtoReflect.Descriptor instead.
func (*VerifyReport) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{37}
}

func (x *VerifyReport) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyReport) GetRecords() int64 {
	if x != nil {
		return x.Records
	}
	return 0
}

func (x *VerifyReport) GetSeals() int64 {
	if x != nil {
		return x.Seals
	}
	return 0
}

func (x *VerifyReport) GetUnsealedTail() int64 {
	if x != nil {
		return x.UnsealedTail
	}
	return 0
}

func (x *VerifyReport) GetTornTail() bool {
	if x != nil {
		return x.TornTail
	}
	return false
}

func (x *VerifyReport) GetHasDefect() bool {
	if x != nil {
		return x.HasDefect
	}
	return false
}

func (x *VerifyReport) GetDefectNo() int64 {
	if x != nil {
		return x.DefectNo
	}
	return 0
}

func (x *VerifyReport) GetDefectReason() string {
	if x != nil {
		return x.DefectReason
	}
	return ""
}

type TableRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Subject   string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Attribute string                 `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	// Time travel: answer as of record number as_of — "what did we know when
	// the ledger stopped at N?". Free by design: the view is folded only up to
	// N. Absent = the current head. (optional: record 0 is a real address.)
	AsOf          *int64 `protobuf:"varint,3,opt,name=as_of,json=asOf,proto3,oneof" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRequest) Reset() {
	*x = TableRequest{}
	mi := &file_api_kivi_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRequest) ProtoMessage() {}

func (x *TableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRequest.ProtoReflect.Descriptor instead.
func (*TableRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{38}
}

func (x *TableRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TableRequest) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *TableRequest) GetAsOf() int64 {
	if x != nil && x.AsOf != nil {
		return *x.AsOf
	}
	return 0
}

type SubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	AsOf          *int64                 `protobuf:"varint,2,opt,name=as_of,json=asOf,proto3,oneof" json:"as_of,omitempty"` // same time-travel contract as TableRequest.as_of
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectRequest) Reset() {
	*x = SubjectRequest{}
	mi := &file_api_kivi_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectRequest) ProtoMessage() {}

func (x *SubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectRequest.ProtoReflect.Descriptor instead.
func (*SubjectRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{39}
}

func (x *SubjectRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubjectRequest) GetAsOf() int64 {
	if x != nil && x.AsOf != nil {
		return *x.AsOf
	}
	return 0
}

// TracedAnswer: value + the events that established it + the ledger scope it
// was derived from. The server never emits one without a trace.
type TracedAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValueJson     string                 `protobuf:"bytes,1,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Trace         []int64                `protobuf:"varint,2,rep,packed,name=trace,proto3" json:"trace,omitempty"`
	Scope         int64                  `protobuf:"varint,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracedAnswer) Reset() {
	*x = TracedAnswer{}
	mi := &file_api_kivi_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracedAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracedAnswer) ProtoMessage() {}

func (x *TracedAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracedAnswer.ProtoReflect.Descriptor instead.
func (*TracedAnswer) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{40}
}

func (x *TracedAnswer) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *TracedAnswer) GetTrace() []int64 {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *TracedAnswer) GetScope() int64 {
	if x != nil {
		return x.Scope
	}
	return 0
}

type ViewState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateJson     string                 `protobuf:"bytes,1,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	Scope         int64                  `protobuf:"varint,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"` // canonical digest — same contract as the ledger
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewState) Reset() {
	*x = ViewState{}
	mi := &file_api_kivi_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewState) ProtoMessage() {}

func (x *ViewState) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewState.ProtoReflect.Descriptor instead.
func (*ViewState) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{41}
}

func (x *ViewState) GetStateJson() string {
	if x != nil {
		return x.StateJson
	}
	return ""
}

func (x *ViewState) GetScope() int64 {
	if x != nil {
		return x.Scope
	}
	return 0
}

func (x *ViewState) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type SeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        string                 `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesRequest) Reset() {
	*x = SeriesRequest{}
	mi := &file_api_kivi_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesRequest) ProtoMessage() {}

func (x *SeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesRequest.ProtoReflect.Descriptor instead.
func (*SeriesRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{42}
}

func (x *SeriesRequest) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

type WhyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trace         []int64                `protobuf:"varint,1,rep,packed,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhyRequest) Reset() {
	*x = WhyRequest{}
	mi := &file_api_kivi_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhyRequest) ProtoMessage() {}

func (x *WhyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhyRequest.ProtoReflect.Descriptor instead.
func (*WhyRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{43}
}

func (x *WhyRequest) GetTrace() []int64 {
	if x != nil {
		return x.Trace
	}
	return nil
}

type RecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*RecordReply         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordList) Reset() {
	*x = RecordList{}
	mi := &file_api_kivi_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordList) ProtoMessage() {}

func (x *RecordList) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordList.ProtoReflect.Descriptor instead.
func (*RecordList) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{44}
}

func (x *RecordList) GetRecords() []*RecordReply {
	if x != nil {
		return x.Records
	}
	return nil
}

type AuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequest) Reset() {
	*x = AuditRequest{}
	mi := &file_api_kivi_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequest) ProtoMessage() {}

func (x *AuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequest.ProtoReflect.Descriptor instead.
func (*AuditRequest) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{45}
}

func (x *AuditRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

type AuditFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Clean         bool                   `protobuf:"varint,2,opt,name=clean,proto3" json:"clean,omitempty"`
	Expected      string                 `protobuf:"bytes,3,opt,name=expected,proto3" json:"expected,omitempty"`
	Found         string                 `protobuf:"bytes,4,opt,name=found,proto3" json:"found,omitempty"`
	ReceiptNo     int64                  `protobuf:"varint,5,opt,name=receipt_no,json=receiptNo,proto3" json:"receipt_no,omitempty"` // defect receipt in the ledger; -1 = none (clean)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditFinding) Reset() {
	*x = AuditFinding{}
	mi := &file_api_kivi_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditFinding) ProtoMessage() {}

func (x *AuditFinding) ProtoReflect() protoreflect.Message {
	mi := &file_api_kivi_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditFinding.ProtoReflect.Descriptor instead.
func (*AuditFinding) Descriptor() ([]byte, []int) {
	return file_api_kivi_proto_rawDescGZIP(), []int{46}
}

func (x *AuditFinding) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *AuditFinding) GetClean() bool {
	if x != nil {
		return x.Clean
	}
	return false
}

func (x *AuditFinding) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *AuditFinding) GetFound() string {
	if x != nil {
		return x.Found
	}
	return ""
}

func (x *AuditFinding) GetReceiptNo() int64 {
	if x != nil {
		return x.ReceiptNo
	}
	return 0
}

var File_api_kivi_proto protoreflect.FileDescriptor

const file_api_kivi_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/kivi.proto\x12\akivi.v1\"O\n" +
	"\tGraphEdge\x12\x1a\n" +
	"\brelation\x18\x01 \x01(\tR\brelation\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x0e\n" +
	"\x02no\x18\x03 \x01(\x03R\x02no\"O\n" +
	"\x15GraphNeighborsRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x18\n" +
	"\x05as_of\x18\x02 \x01(\x03H\x00R\x04asOf\x88\x01\x01B\b\n" +
	"\x06_as_of\"T\n" +
	"\n" +
	"GraphEdges\x12(\n" +
	"\x05edges\x18\x01 \x03(\v2\x12.kivi.v1.GraphEdgeR\x05edges\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"{\n" +
	"\x15GraphReachableRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x03R\x05depth\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x18\n" +
	"\x05as_of\x18\x04 \x01(\x03H\x00R\x04asOf\x88\x01\x01B\b\n" +
	"\x06_as_of\"N\n" +
	"\fGraphReached\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x03R\x05depth\x12\x14\n" +
	"\x05trace\x18\x03 \x03(\x03R\x05trace\"`\n" +
	"\x13GraphReachableReply\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.kivi.v1.GraphReachedR\x05nodes\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"p\n" +
	"\x10GraphPathRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x03R\x05depth\x12\x18\n" +
	"\x05as_of\x18\x04 \x01(\x03H\x00R\x04asOf\x88\x01\x01B\b\n" +
	"\x06_as_of\"Z\n" +
	"\bGraphHop\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x0e\n" +
	"\x02no\x18\x04 \x01(\x03R\x02no\"k\n" +
	"\x0eGraphPathReply\x12%\n" +
	"\x04hops\x18\x01 \x03(\v2\x11.kivi.v1.GraphHopR\x04hops\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"T\n" +
	"\x10SubscribeRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x14\n" +
	"\x05types\x18\x03 \x03(\tR\x05types\"|\n" +
	"\x0fViewPageRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12\x1b\n" +
	"\tafter_key\x18\x02 \x01(\tR\bafterKey\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x18\n" +
	"\x05as_of\x18\x04 \x01(\x03H\x00R\x04asOf\x88\x01\x01B\b\n" +
	"\x06_as_of\"<\n" +
	"\tViewEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\"}\n" +
	"\bViewPage\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.kivi.v1.ViewEntryR\aentries\x12\x19\n" +
	"\bnext_key\x18\x02 \x01(\tR\anextKey\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\x03R\x05scope\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\"A\n" +
	"\tHeadReply\x12\x17\n" +
	"\ahead_no\x18\x01 \x01(\x03R\x06headNo\x12\x1b\n" +
	"\thead_hash\x18\x02 \x01(\tR\bheadHash\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Y\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12!\n" +
	"\fexpires_unix\x18\x03 \x01(\x03R\vexpiresUnix\"4\n" +
	"\x0eSimilarRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\x03R\x01k\"S\n" +
	"\n" +
	"SimilarHit\x12\x0e\n" +
	"\x02no\x18\x01 \x01(\x03R\x02no\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x1f\n" +
	"\vrecord_json\x18\x03 \x01(\tR\n" +
	"recordJson\"c\n" +
	"\fSimilarReply\x12'\n" +
	"\x04hits\x18\x01 \x03(\v2\x13.kivi.v1.SimilarHitR\x04hits\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\x03R\x05scope\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"u\n" +
	"\vVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\tR\tcandidate\x12\x1b\n" +
	"\tlast_term\x18\x03 \x01(\x03R\blastTerm\x12\x17\n" +
	"\alast_no\x18\x04 \x01(\x03R\x06lastNo\"9\n" +
	"\tVoteReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\agranted\x18\x02 \x01(\bR\agranted\"V\n" +
	"\vBeatRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\tR\x06leader\x12\x1b\n" +
	"\tcommit_no\x18\x03 \x01(\x03R\bcommitNo\"\x1f\n" +
	"\tBeatReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\"Y\n" +
	"\fReplicateAck\x12\x1a\n" +
	"\bfollower\x18\x01 \x01(\tR\bfollower\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x19\n" +
	"\backed_no\x18\x03 \x01(\x03R\aackedNo\"$\n" +
	"\x0eWitnessRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\"\x8f\x01\n" +
	"\vAttestation\x12\x0e\n" +
	"\x02pk\x18\x01 \x01(\tR\x02pk\x12\x17\n" +
	"\aseal_no\x18\x02 \x01(\x03R\x06sealNo\x12\x1d\n" +
	"\n" +
	"covered_no\x18\x03 \x01(\x03R\tcoveredNo\x12\x1b\n" +
	"\thead_hash\x18\x04 \x01(\tR\bheadHash\x12\x1b\n" +
	"\tseal_json\x18\x05 \x01(\tR\bsealJson\"\x87\x01\n" +
	"\rBackupRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12 \n" +
	"\vincremental\x18\x02 \x01(\bR\vincremental\x12\x19\n" +
	"\bsince_no\x18\x03 \x01(\x03R\asinceNo\x12\x1d\n" +
	"\n" +
	"since_hash\x18\x04 \x01(\tR\tsinceHash\"!\n" +
	"\vBackupChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x80\x01\n" +
	"\n" +
	"RotateInfo\x12\x16\n" +
	"\x06period\x18\x01 \x01(\x03R\x06period\x12\x18\n" +
	"\aarchive\x18\x02 \x01(\tR\aarchive\x12%\n" +
	"\x0earchive_sha256\x18\x03 \x01(\tR\rarchiveSha256\x12\x19\n" +
	"\bfirst_no\x18\x04 \x01(\x03R\afirstNo\"\a\n" +
	"\x05Empty\"r\n" +
	"\rAppendRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tbody_json\x18\x02 \x01(\tR\bbodyJson\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12\x16\n" +
	"\x06schema\x18\x04 \x01(\x03R\x06schema\"E\n" +
	"\aReceipt\x12\x0e\n" +
	"\x02no\x18\x01 \x01(\x03R\x02no\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\";\n" +
	"\vReceiptList\x12,\n" +
	"\breceipts\x18\x01 \x03(\v2\x10.kivi.v1.ReceiptR\breceipts\"6\n" +
	"\fEraseRequest\x12\x0e\n" +
	"\x02no\x18\x01 \x01(\x03R\x02no\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\":\n" +
	"\x10GetRecordRequest\x12\x0e\n" +
	"\x02no\x18\x01 \x01(\x03R\x02no\x12\x16\n" +
	"\x06unseal\x18\x02 \x01(\bR\x06unseal\".\n" +
	"\vRecordReply\x12\x1f\n" +
	"\vrecord_json\x18\x01 \x01(\tR\n" +
	"recordJson\";\n" +
	"\rReplayRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"\xf1\x01\n" +
	"\fVerifyReport\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\arecords\x18\x02 \x01(\x03R\arecords\x12\x14\n" +
	"\x05seals\x18\x03 \x01(\x03R\x05seals\x12#\n" +
	"\runsealed_tail\x18\x04 \x01(\x03R\funsealedTail\x12\x1b\n" +
	"\ttorn_tail\x18\x05 \x01(\bR\btornTail\x12\x1d\n" +
	"\n" +
	"has_defect\x18\x06 \x01(\bR\thasDefect\x12\x1b\n" +
	"\tdefect_no\x18\a \x01(\x03R\bdefectNo\x12#\n" +
	"\rdefect_reason\x18\b \x01(\tR\fdefectReason\"j\n" +
	"\fTableRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1c\n" +
	"\tattribute\x18\x02 \x01(\tR\tattribute\x12\x18\n" +
	"\x05as_of\x18\x03 \x01(\x03H\x00R\x04asOf\x88\x01\x01B\b\n" +
	"\x06_as_of\"N\n" +
	"\x0eSubjectRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x18\n" +
	"\x05as_of\x18\x02 \x01(\x03H\x00R\x04asOf\x88\x01\x01B\b\n" +
	"\x06_as_of\"Y\n" +
	"\fTracedAnswer\x12\x1d\n" +
	"\n" +
	"value_json\x18\x01 \x01(\tR\tvalueJson\x12\x14\n" +
	"\x05trace\x18\x02 \x03(\x03R\x05trace\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\x03R\x05scope\"T\n" +
	"\tViewState\x12\x1d\n" +
	"\n" +
	"state_json\x18\x01 \x01(\tR\tstateJson\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\x03R\x05scope\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\"'\n" +
	"\rSeriesRequest\x12\x16\n" +
	"\x06series\x18\x01 \x01(\tR\x06series\"\"\n" +
	"\n" +
	"WhyRequest\x12\x14\n" +
	"\x05trace\x18\x01 \x03(\x03R\x05trace\"<\n" +
	"\n" +
	"RecordList\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.kivi.v1.RecordReplyR\arecords\"\"\n" +
	"\fAuditRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\"\x89\x01\n" +
	"\fAuditFinding\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12\x14\n" +
	"\x05clean\x18\x02 \x01(\bR\x05clean\x12\x1a\n" +
	"\bexpected\x18\x03 \x01(\tR\bexpected\x12\x14\n" +
	"\x05found\x18\x04 \x01(\tR\x05found\x12\x1d\n" +
	"\n" +
	"receipt_no\x18\x05 \x01(\x03R\treceiptNo2\xed\f\n" +
	"\x04Kivi\x122\n" +
	"\x06Append\x12\x16.kivi.v1.AppendRequest\x1a\x10.kivi.v1.Receipt\x12=\n" +
	"\vAppendBatch\x12\x16.kivi.v1.AppendRequest\x1a\x14.kivi.v1.ReceiptList(\x01\x129\n" +
	"\rAppendPrivate\x12\x16.kivi.v1.AppendRequest\x1a\x10.kivi.v1.Receipt\x120\n" +
	"\x05Erase\x12\x15.kivi.v1.EraseRequest\x1a\x10.kivi.v1.Receipt\x12<\n" +
	"\tGetRecord\x12\x19.kivi.v1.GetRecordRequest\x1a\x14.kivi.v1.RecordReply\x128\n" +
	"\x06Replay\x12\x16.kivi.v1.ReplayRequest\x1a\x14.kivi.v1.RecordReply0\x01\x12/\n" +
	"\x06Verify\x12\x0e.kivi.v1.Empty\x1a\x15.kivi.v1.VerifyReport\x12:\n" +
	"\n" +
	"QueryTable\x12\x15.kivi.v1.TableRequest\x1a\x15.kivi.v1.TracedAnswer\x12>\n" +
	"\fQuerySubject\x12\x17.kivi.v1.SubjectRequest\x1a\x15.kivi.v1.TracedAnswer\x120\n" +
	"\n" +
	"QueryGraph\x12\x0e.kivi.v1.Empty\x1a\x12.kivi.v1.ViewState\x129\n" +
	"\vQuerySeries\x12\x16.kivi.v1.SeriesRequest\x1a\x12.kivi.v1.ViewState\x12/\n" +
	"\x03Why\x12\x13.kivi.v1.WhyRequest\x1a\x13.kivi.v1.RecordList\x125\n" +
	"\x05Audit\x12\x15.kivi.v1.AuditRequest\x1a\x15.kivi.v1.AuditFinding\x12(\n" +
	"\x04Seal\x12\x0e.kivi.v1.Empty\x1a\x10.kivi.v1.Receipt\x12-\n" +
	"\x06Rotate\x12\x0e.kivi.v1.Empty\x1a\x13.kivi.v1.RotateInfo\x128\n" +
	"\x06Backup\x12\x16.kivi.v1.BackupRequest\x1a\x14.kivi.v1.BackupChunk0\x01\x12.\n" +
	"\x06Attest\x12\x0e.kivi.v1.Empty\x1a\x14.kivi.v1.Attestation\x120\n" +
	"\x04Vote\x12\x14.kivi.v1.VoteRequest\x1a\x12.kivi.v1.VoteReply\x120\n" +
	"\x04Beat\x12\x14.kivi.v1.BeatRequest\x1a\x12.kivi.v1.BeatReply\x12<\n" +
	"\tReplicate\x12\x15.kivi.v1.ReplicateAck\x1a\x14.kivi.v1.RecordReply(\x010\x01\x124\n" +
	"\aWitness\x12\x17.kivi.v1.WitnessRequest\x1a\x10.kivi.v1.Receipt\x129\n" +
	"\aSimilar\x12\x17.kivi.v1.SimilarRequest\x1a\x15.kivi.v1.SimilarReply\x123\n" +
	"\x05Login\x12\x15.kivi.v1.LoginRequest\x1a\x13.kivi.v1.LoginReply\x12*\n" +
	"\x04Head\x12\x0e.kivi.v1.Empty\x1a\x12.kivi.v1.HeadReply\x12<\n" +
	"\rQueryViewPage\x12\x18.kivi.v1.ViewPageRequest\x1a\x11.kivi.v1.ViewPage\x12>\n" +
	"\tSubscribe\x12\x19.kivi.v1.SubscribeRequest\x1a\x14.kivi.v1.RecordReply0\x01\x12E\n" +
	"\x0eGraphNeighbors\x12\x1e.kivi.v1.GraphNeighborsRequest\x1a\x13.kivi.v1.GraphEdges\x12N\n" +
	"\x0eGraphReachable\x12\x1e.kivi.v1.GraphReachableRequest\x1a\x1c.kivi.v1.GraphReachableReply\x12?\n" +
	"\tGraphPath\x12\x19.kivi.v1.GraphPathRequest\x1a\x17.kivi.v1.GraphPathReplyB\n" +
	"Z\bkivi/apib\x06proto3"

var (
	file_api_kivi_proto_rawDescOnce sync.Once
	file_api_kivi_proto_rawDescData []byte
)

func file_api_kivi_proto_rawDescGZIP() []byte {
	file_api_kivi_proto_rawDescOnce.Do(func() {
		file_api_kivi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kivi_proto_rawDesc), len(file_api_kivi_proto_rawDesc)))
	})
	return file_api_kivi_proto_rawDescData
}

var file_api_kivi_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_api_kivi_proto_goTypes = []any{
	(*GraphEdge)(nil),             // 0: kivi.v1.GraphEdge
	(*GraphNeighborsRequest)(nil), // 1: kivi.v1.GraphNeighborsRequest
	(*GraphEdges)(nil),            // 2: kivi.v1.GraphEdges
	(*GraphReachableRequest)(nil), // 3: kivi.v1.GraphReachableRequest
	(*GraphReached)(nil),          // 4: kivi.v1.GraphReached
	(*GraphReachableReply)(nil),   // 5: kivi.v1.GraphReachableReply
	(*GraphPathRequest)(nil),      // 6: kivi.v1.GraphPathRequest
	(*GraphHop)(nil),              // 7: kivi.v1.GraphHop
	(*GraphPathReply)(nil),        // 8: kivi.v1.GraphPathReply
	(*SubscribeRequest)(nil),      // 9: kivi.v1.SubscribeRequest
	(*ViewPageRequest)(nil),       // 10: kivi.v1.ViewPageRequest
	(*ViewEntry)(nil),             // 11: kivi.v1.ViewEntry
	(*ViewPage)(nil),              // 12: kivi.v1.ViewPage
	(*HeadReply)(nil),             // 13: kivi.v1.HeadReply
	(*LoginRequest)(nil),          // 14: kivi.v1.LoginRequest
	(*LoginReply)(nil),            // 15: kivi.v1.LoginReply
	(*SimilarRequest)(nil),        // 16: kivi.v1.SimilarRequest
	(*SimilarHit)(nil),            // 17: kivi.v1.SimilarHit
	(*SimilarReply)(nil),          // 18: kivi.v1.SimilarReply
	(*VoteRequest)(nil),           // 19: kivi.v1.VoteRequest
	(*VoteReply)(nil),             // 20: kivi.v1.VoteReply
	(*BeatRequest)(nil),           // 21: kivi.v1.BeatRequest
	(*BeatReply)(nil),             // 22: kivi.v1.BeatReply
	(*ReplicateAck)(nil),          // 23: kivi.v1.ReplicateAck
	(*WitnessRequest)(nil),        // 24: kivi.v1.WitnessRequest
	(*Attestation)(nil),           // 25: kivi.v1.Attestation
	(*BackupRequest)(nil),         // 26: kivi.v1.BackupRequest
	(*BackupChunk)(nil),           // 27: kivi.v1.BackupChunk
	(*RotateInfo)(nil),            // 28: kivi.v1.RotateInfo
	(*Empty)(nil),                 // 29: kivi.v1.Empty
	(*AppendRequest)(nil),         // 30: kivi.v1.AppendRequest
	(*Receipt)(nil),               // 31: kivi.v1.Receipt
	(*ReceiptList)(nil),           // 32: kivi.v1.ReceiptList
	(*EraseRequest)(nil),          // 33: kivi.v1.EraseRequest
	(*GetRecordRequest)(nil),      // 34: kivi.v1.GetRecordRequest
	(*RecordReply)(nil),           // 35: kivi.v1.RecordReply
	(*ReplayRequest)(nil),         // 36: kivi.v1.ReplayRequest
	(*VerifyReport)(nil),          // 37: kivi.v1.VerifyReport
	(*TableRequest)(nil),          // 38: kivi.v1.TableRequest
	(*SubjectRequest)(nil),        // 39: kivi.v1.SubjectRequest
	(*TracedAnswer)(nil),          // 40: kivi.v1.TracedAnswer
	(*ViewState)(nil),             // 41: kivi.v1.ViewState
	(*SeriesRequest)(nil),         // 42: kivi.v1.SeriesRequest
	(*WhyRequest)(nil),            // 43: kivi.v1.WhyRequest
	(*RecordList)(nil),            // 44: kivi.v1.RecordList
	(*AuditRequest)(nil),          // 45: kivi.v1.AuditRequest
	(*AuditFinding)(nil),          // 46: kivi.v1.AuditFinding
}
var file_api_kivi_proto_depIdxs = []int32{
	0,  // 0: kivi.v1.GraphEdges.edges:type_name -> kivi.v1.GraphEdge
	4,  // 1: kivi.v1.GraphReachableReply.nodes:type_name -> kivi.v1.GraphReached
	7,  // 2: kivi.v1.GraphPathReply.hops:type_name -> kivi.v1.GraphHop
	11, // 3: kivi.v1.ViewPage.entries:type_name -> kivi.v1.ViewEntry
	17, // 4: kivi.v1.SimilarReply.hits:type_name -> kivi.v1.SimilarHit
	31, // 5: kivi.v1.ReceiptList.receipts:type_name -> kivi.v1.Receipt
	35, // 6: kivi.v1.RecordList.records:type_name -> kivi.v1.RecordReply
	30, // 7: kivi.v1.Kivi.Append:input_type -> kivi.v1.AppendRequest
	30, // 8: kivi.v1.Kivi.AppendBatch:input_type -> kivi.v1.AppendRequest
	30, // 9: kivi.v1.Kivi.AppendPrivate:input_type -> kivi.v1.AppendRequest
	33, // 10: kivi.v1.Kivi.Erase:input_type -> kivi.v1.EraseRequest
	34, // 11: kivi.v1.Kivi.GetRecord:input_type -> kivi.v1.GetRecordRequest
	36, // 12: kivi.v1.Kivi.Replay:input_type -> kivi.v1.ReplayRequest
	29, // 13: kivi.v1.Kivi.Verify:input_type -> kivi.v1.Empty
	38, // 14: kivi.v1.Kivi.QueryTable:input_type -> kivi.v1.TableRequest
	39, // 15: kivi.v1.Kivi.QuerySubject:input_type -> kivi.v1.SubjectRequest
	29, // 16: kivi.v1.Kivi.QueryGraph:input_type -> kivi.v1.Empty
	42, // 17: kivi.v1.Kivi.QuerySeries:input_type -> kivi.v1.SeriesRequest
	43, // 18: kivi.v1.Kivi.Why:input_type -> kivi.v1.WhyRequest
	45, // 19: kivi.v1.Kivi.Audit:input_type -> kivi.v1.AuditRequest
	29, // 20: kivi.v1.Kivi.Seal:input_type -> kivi.v1.Empty
	29, // 21: kivi.v1.Kivi.Rotate:input_type -> kivi.v1.Empty
	26, // 22: kivi.v1.Kivi.Backup:input_type -> kivi.v1.BackupRequest
	29, // 23: kivi.v1.Kivi.Attest:input_type -> kivi.v1.Empty
	19, // 24: kivi.v1.Kivi.Vote:input_type -> kivi.v1.VoteRequest
	21, // 25: kivi.v1.Kivi.Beat:input_type -> kivi.v1.BeatRequest
	23, // 26: kivi.v1.Kivi.Replicate:input_type -> kivi.v1.ReplicateAck
	24, // 27: kivi.v1.Kivi.Witness:input_type -> kivi.v1.WitnessRequest
	16, // 28: kivi.v1.Kivi.Similar:input_type -> kivi.v1.SimilarRequest
	14, // 29: kivi.v1.Kivi.Login:input_type -> kivi.v1.LoginRequest
	29, // 30: kivi.v1.Kivi.Head:input_type -> kivi.v1.Empty
	10, // 31: kivi.v1.Kivi.QueryViewPage:input_type -> kivi.v1.ViewPageRequest
	9,  // 32: kivi.v1.Kivi.Subscribe:input_type -> kivi.v1.SubscribeRequest
	1,  // 33: kivi.v1.Kivi.GraphNeighbors:input_type -> kivi.v1.GraphNeighborsRequest
	3,  // 34: kivi.v1.Kivi.GraphReachable:input_type -> kivi.v1.GraphReachableRequest
	6,  // 35: kivi.v1.Kivi.GraphPath:input_type -> kivi.v1.GraphPathRequest
	31, // 36: kivi.v1.Kivi.Append:output_type -> kivi.v1.Receipt
	32, // 37: kivi.v1.Kivi.AppendBatch:output_type -> kivi.v1.ReceiptList
	31, // 38: kivi.v1.Kivi.AppendPrivate:output_type -> kivi.v1.Receipt
	31, // 39: kivi.v1.Kivi.Erase:output_type -> kivi.v1.Receipt
	35, // 40: kivi.v1.Kivi.GetRecord:output_type -> kivi.v1.RecordReply
	35, // 41: kivi.v1.Kivi.Replay:output_type -> kivi.v1.RecordReply
	37, // 42: kivi.v1.Kivi.Verify:output_type -> kivi.v1.VerifyReport
	40, // 43: kivi.v1.Kivi.QueryTable:output_type -> kivi.v1.TracedAnswer
	40, // 44: kivi.v1.Kivi.QuerySubject:output_type -> kivi.v1.TracedAnswer
	41, // 45: kivi.v1.Kivi.QueryGraph:output_type -> kivi.v1.ViewState
	41, // 46: kivi.v1.Kivi.QuerySeries:output_type -> kivi.v1.ViewState
	44, // 47: kivi.v1.Kivi.Why:output_type -> kivi.v1.RecordList
	46, // 48: kivi.v1.Kivi.Audit:output_type -> kivi.v1.AuditFinding
	31, // 49: kivi.v1.Kivi.Seal:output_type -> kivi.v1.Receipt
	28, // 50: kivi.v1.Kivi.Rotate:output_type -> kivi.v1.RotateInfo
	27, // 51: kivi.v1.Kivi.Backup:output_type -> kivi.v1.BackupChunk
	25, // 52: kivi.v1.Kivi.Attest:output_type -> kivi.v1.Attestation
	20, // 53: kivi.v1.Kivi.Vote:output_type -> kivi.v1.VoteReply
	22, // 54: kivi.v1.Kivi.Beat:output_type -> kivi.v1.BeatReply
	35, // 55: kivi.v1.Kivi.Replicate:output_type -> kivi.v1.RecordReply
	31, // 56: kivi.v1.Kivi.Witness:output_type -> kivi.v1.Receipt
	18, // 57: kivi.v1.Kivi.Similar:output_type -> kivi.v1.SimilarReply
	15, // 58: kivi.v1.Kivi.Login:output_type -> kivi.v1.LoginReply
	13, // 59: kivi.v1.Kivi.Head:output_type -> kivi.v1.HeadReply
	12, // 60: kivi.v1.Kivi.QueryViewPage:output_type -> kivi.v1.ViewPage
	35, // 61: kivi.v1.Kivi.Subscribe:output_type -> kivi.v1.RecordReply
	2,  // 62: kivi.v1.Kivi.GraphNeighbors:output_type -> kivi.v1.GraphEdges
	5,  // 63: kivi.v1.Kivi.GraphReachable:output_type -> kivi.v1.GraphReachableReply
	8,  // 64: kivi.v1.Kivi.GraphPath:output_type -> kivi.v1.GraphPathReply
	36, // [36:65] is the sub-list for method output_type
	7,  // [7:36] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_kivi_proto_init() }
func file_api_kivi_proto_init() {
	if File_api_kivi_proto != nil {
		return
	}
	file_api_kivi_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_kivi_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_kivi_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_kivi_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_kivi_proto_msgTypes[38].OneofWrappers = []any{}
	file_api_kivi_proto_msgTypes[39].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kivi_proto_rawDesc), len(file_api_kivi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kivi_proto_goTypes,
		DependencyIndexes: file_api_kivi_proto_depIdxs,
		MessageInfos:      file_api_kivi_proto_msgTypes,
	}.Build()
	File_api_kivi_proto = out.File
	file_api_kivi_proto_goTypes = nil
	file_api_kivi_proto_depIdxs = nil
}
