// kivi gRPC contract, v1 — THE single source of truth for the data plane
// (PLAN2 F3). Freezing rule: a published field number is never changed or
// reused; additions only.
//
// Bodies, records and view states travel as CANONICAL JSON STRINGS, not as
// protobuf structs: format v1 is JSON-native and google.protobuf.Struct would
// lose int64 fidelity (its numbers are doubles). The JSON string preserves the
// exact bytes the ledger reasons about.
//
// Honesty note: proto3 cannot mark fields required — the "no answer without a
// trace" guarantee (trace/scope always present) is enforced by the server test
// suite instead.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/kivi.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kivi_Append_FullMethodName         = "/kivi.v1.Kivi/Append"
	Kivi_AppendBatch_FullMethodName    = "/kivi.v1.Kivi/AppendBatch"
	Kivi_AppendPrivate_FullMethodName  = "/kivi.v1.Kivi/AppendPrivate"
	Kivi_Erase_FullMethodName          = "/kivi.v1.Kivi/Erase"
	Kivi_GetRecord_FullMethodName      = "/kivi.v1.Kivi/GetRecord"
	Kivi_Replay_FullMethodName         = "/kivi.v1.Kivi/Replay"
	Kivi_Verify_FullMethodName         = "/kivi.v1.Kivi/Verify"
	Kivi_QueryTable_FullMethodName     = "/kivi.v1.Kivi/QueryTable"
	Kivi_QuerySubject_FullMethodName   = "/kivi.v1.Kivi/QuerySubject"
	Kivi_QueryGraph_FullMethodName     = "/kivi.v1.Kivi/QueryGraph"
	Kivi_QuerySeries_FullMethodName    = "/kivi.v1.Kivi/QuerySeries"
	Kivi_Why_FullMethodName            = "/kivi.v1.Kivi/Why"
	Kivi_Audit_FullMethodName          = "/kivi.v1.Kivi/Audit"
	Kivi_Seal_FullMethodName           = "/kivi.v1.Kivi/Seal"
	Kivi_Rotate_FullMethodName         = "/kivi.v1.Kivi/Rotate"
	Kivi_Backup_FullMethodName         = "/kivi.v1.Kivi/Backup"
	Kivi_Attest_FullMethodName         = "/kivi.v1.Kivi/Attest"
	Kivi_Vote_FullMethodName           = "/kivi.v1.Kivi/Vote"
	Kivi_Beat_FullMethodName           = "/kivi.v1.Kivi/Beat"
	Kivi_Replicate_FullMethodName      = "/kivi.v1.Kivi/Replicate"
	Kivi_Witness_FullMethodName        = "/kivi.v1.Kivi/Witness"
	Kivi_Similar_FullMethodName        = "/kivi.v1.Kivi/Similar"
	Kivi_Login_FullMethodName          = "/kivi.v1.Kivi/Login"
	Kivi_Head_FullMethodName           = "/kivi.v1.Kivi/Head"
	Kivi_QueryViewPage_FullMethodName  = "/kivi.v1.Kivi/QueryViewPage"
	Kivi_Subscribe_FullMethodName      = "/kivi.v1.Kivi/Subscribe"
	Kivi_GraphNeighbors_FullMethodName = "/kivi.v1.Kivi/GraphNeighbors"
	Kivi_GraphReachable_FullMethodName = "/kivi.v1.Kivi/GraphReachable"
	Kivi_GraphPath_FullMethodName      = "/kivi.v1.Kivi/GraphPath"
)

// KiviClient is the client API for Kivi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KiviClient interface {
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*Receipt, error)
	AppendBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AppendRequest, ReceiptList], error)
	AppendPrivate(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*Receipt, error)
	Erase(ctx context.Context, in *EraseRequest, opts ...grpc.CallOption) (*Receipt, error)
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*RecordReply, error)
	Replay(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecordReply], error)
	Verify(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VerifyReport, error)
	QueryTable(ctx context.Context, in *TableRequest, opts ...grpc.CallOption) (*TracedAnswer, error)
	// QuerySubject (G15): TableRequest's whole-row sibling. QueryTable answers
	// one (subject, attribute) cell; a caller that doesn't already know which
	// attributes exist for a subject had no way to ask "what do we know about
	// X?" without paging the whole table (QueryViewPage) hunting for one key.
	// Same traced contract, same view (Table) and cache tiers underneath —
	// this is a new EXTRACTION over an index that already existed, not a new
	// index: the value_json is the whole row {attribute: value, ...} and the
	// trace is the union of every event that established any cell in it.
	QuerySubject(ctx context.Context, in *SubjectRequest, opts ...grpc.CallOption) (*TracedAnswer, error)
	QueryGraph(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ViewState, error)
	QuerySeries(ctx context.Context, in *SeriesRequest, opts ...grpc.CallOption) (*ViewState, error)
	Why(ctx context.Context, in *WhyRequest, opts ...grpc.CallOption) (*RecordList, error)
	Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditFinding, error)
	Seal(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Receipt, error)
	Rotate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RotateInfo, error)
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupChunk], error)
	Attest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Attestation, error)
	// Cluster plane (G8, PLAN4): Raft-style election + quorum-acked replication.
	// Only meaningful when KIVI_CLUSTER is set; single-node servers answer
	// FailedPrecondition.
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error)
	Beat(ctx context.Context, in *BeatRequest, opts ...grpc.CallOption) (*BeatReply, error)
	// The follower opens the stream to the LEADER: the leader pushes records,
	// the follower sends acks on the same stream. Acks drive the commit index.
	Replicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicateAck, RecordReply], error)
	// Federation (PLAN6): fetch a fresh attestation from a peer and FILE it in
	// this ledger as a kivi.witness event — mutual testimony without consensus.
	Witness(ctx context.Context, in *WitnessRequest, opts ...grpc.CallOption) (*Receipt, error)
	// Semantic view (PLAN7): traced similarity search. Every hit is a record
	// number with its score and raw record; the reply names the model and the
	// covered scope — an untraced score does not exist.
	Similar(ctx context.Context, in *SimilarRequest, opts ...grpc.CallOption) (*SimilarReply, error)
	// Identity plane (PLAN8): password login → session token (Bearer). User
	// management itself is receipted kivi.user events (admin plane / local CLI).
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// Head is the cheap orientation call: the ledger's last record number and
	// head hash, straight from the open writer — NO cryptographic audit runs.
	// Tail readers (recent_events, pagination) should use this, and reach for
	// Verify only when integrity itself is the question.
	Head(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeadReply, error)
	// Paged view reads: deterministic KEYSET pagination over a compiled view's
	// canonical (sorted) keys — no offsets, no drift. Snapshot pinning: page 1
	// answers with the scope it folded to; pass that scope back as as_of on
	// later pages and EVERY page describes the same moment (time travel reused
	// as pagination glue). Record streams page differently: Replay(from) — the
	// record number IS the cursor.
	QueryViewPage(ctx context.Context, in *ViewPageRequest, opts ...grpc.CallOption) (*ViewPage, error)
	// Subscribe (G14): a TYPE-FILTERED live feed for point consumers that only
	// care about one or two event types (a worker fed only kivi.apikey, a
	// dashboard fed only kivi.metric) — the same live-tail mechanism as Replay,
	// but the server drops non-matching records before they cross the wire
	// instead of making every consumer receive and discard everything.
	//
	// Honesty note: filtering BY DESIGN creates gaps in the record numbering,
	// so this stream does NOT carry Replay's gapless/chain-adjacency promise —
	// each delivered record's OWN hash (and seal signature, for kivi.seal
	// records) is still independently verifiable, proving "byte-exact what the
	// ledger holds," but never "you received everything." A consumer that
	// needs the stronger, audit-grade guarantee (replicas, backup, CDC that
	// must prove no record was skipped) uses Replay — unfiltered — instead.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecordReply], error)
	// Graph traversal over `relation` events (traced, bounded, as-of). The server
	// folds relations into an adjacency and walks it; every answer carries the
	// record numbers of the edges it crossed. Reader role.
	GraphNeighbors(ctx context.Context, in *GraphNeighborsRequest, opts ...grpc.CallOption) (*GraphEdges, error)
	GraphReachable(ctx context.Context, in *GraphReachableRequest, opts ...grpc.CallOption) (*GraphReachableReply, error)
	GraphPath(ctx context.Context, in *GraphPathRequest, opts ...grpc.CallOption) (*GraphPathReply, error)
}

type kiviClient struct {
	cc grpc.ClientConnInterface
}

func NewKiviClient(cc grpc.ClientConnInterface) KiviClient {
	return &kiviClient{cc}
}

func (c *kiviClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Kivi_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) AppendBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AppendRequest, ReceiptList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kivi_ServiceDesc.Streams[0], Kivi_AppendBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AppendRequest, ReceiptList]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kivi_AppendBatchClient = grpc.ClientStreamingClient[AppendRequest, ReceiptList]

func (c *kiviClient) AppendPrivate(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Kivi_AppendPrivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Erase(ctx context.Context, in *EraseRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Kivi_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*RecordReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordReply)
	err := c.cc.Invoke(ctx, Kivi_GetRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Replay(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecordReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kivi_ServiceDesc.Streams[1], Kivi_Replay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplayRequest, RecordReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kivi_ReplayClient = grpc.ServerStreamingClient[RecordReply]

func (c *kiviClient) Verify(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VerifyReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyReport)
	err := c.cc.Invoke(ctx, Kivi_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) QueryTable(ctx context.Context, in *TableRequest, opts ...grpc.CallOption) (*TracedAnswer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TracedAnswer)
	err := c.cc.Invoke(ctx, Kivi_QueryTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) QuerySubject(ctx context.Context, in *SubjectRequest, opts ...grpc.CallOption) (*TracedAnswer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TracedAnswer)
	err := c.cc.Invoke(ctx, Kivi_QuerySubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) QueryGraph(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ViewState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewState)
	err := c.cc.Invoke(ctx, Kivi_QueryGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) QuerySeries(ctx context.Context, in *SeriesRequest, opts ...grpc.CallOption) (*ViewState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewState)
	err := c.cc.Invoke(ctx, Kivi_QuerySeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Why(ctx context.Context, in *WhyRequest, opts ...grpc.CallOption) (*RecordList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordList)
	err := c.cc.Invoke(ctx, Kivi_Why_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditFinding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditFinding)
	err := c.cc.Invoke(ctx, Kivi_Audit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Seal(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Kivi_Seal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Rotate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RotateInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateInfo)
	err := c.cc.Invoke(ctx, Kivi_Rotate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kivi_ServiceDesc.Streams[2], Kivi_Backup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackupRequest, BackupChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kivi_BackupClient = grpc.ServerStreamingClient[BackupChunk]

func (c *kiviClient) Attest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Attestation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attestation)
	err := c.cc.Invoke(ctx, Kivi_Attest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteReply)
	err := c.cc.Invoke(ctx, Kivi_Vote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Beat(ctx context.Context, in *BeatRequest, opts ...grpc.CallOption) (*BeatReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeatReply)
	err := c.cc.Invoke(ctx, Kivi_Beat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicateAck, RecordReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kivi_ServiceDesc.Streams[3], Kivi_Replicate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplicateAck, RecordReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kivi_ReplicateClient = grpc.BidiStreamingClient[ReplicateAck, RecordReply]

func (c *kiviClient) Witness(ctx context.Context, in *WitnessRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Kivi_Witness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Similar(ctx context.Context, in *SimilarRequest, opts ...grpc.CallOption) (*SimilarReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimilarReply)
	err := c.cc.Invoke(ctx, Kivi_Similar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, Kivi_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Head(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeadReply)
	err := c.cc.Invoke(ctx, Kivi_Head_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) QueryViewPage(ctx context.Context, in *ViewPageRequest, opts ...grpc.CallOption) (*ViewPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewPage)
	err := c.cc.Invoke(ctx, Kivi_QueryViewPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecordReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kivi_ServiceDesc.Streams[4], Kivi_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, RecordReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kivi_SubscribeClient = grpc.ServerStreamingClient[RecordReply]

func (c *kiviClient) GraphNeighbors(ctx context.Context, in *GraphNeighborsRequest, opts ...grpc.CallOption) (*GraphEdges, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphEdges)
	err := c.cc.Invoke(ctx, Kivi_GraphNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) GraphReachable(ctx context.Context, in *GraphReachableRequest, opts ...grpc.CallOption) (*GraphReachableReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphReachableReply)
	err := c.cc.Invoke(ctx, Kivi_GraphReachable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiviClient) GraphPath(ctx context.Context, in *GraphPathRequest, opts ...grpc.CallOption) (*GraphPathReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphPathReply)
	err := c.cc.Invoke(ctx, Kivi_GraphPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KiviServer is the server API for Kivi service.
// All implementations must embed UnimplementedKiviServer
// for forward compatibility.
type KiviServer interface {
	Append(context.Context, *AppendRequest) (*Receipt, error)
	AppendBatch(grpc.ClientStreamingServer[AppendRequest, ReceiptList]) error
	AppendPrivate(context.Context, *AppendRequest) (*Receipt, error)
	Erase(context.Context, *EraseRequest) (*Receipt, error)
	GetRecord(context.Context, *GetRecordRequest) (*RecordReply, error)
	Replay(*ReplayRequest, grpc.ServerStreamingServer[RecordReply]) error
	Verify(context.Context, *Empty) (*VerifyReport, error)
	QueryTable(context.Context, *TableRequest) (*TracedAnswer, error)
	// QuerySubject (G15): TableRequest's whole-row sibling. QueryTable answers
	// one (subject, attribute) cell; a caller that doesn't already know which
	// attributes exist for a subject had no way to ask "what do we know about
	// X?" without paging the whole table (QueryViewPage) hunting for one key.
	// Same traced contract, same view (Table) and cache tiers underneath —
	// this is a new EXTRACTION over an index that already existed, not a new
	// index: the value_json is the whole row {attribute: value, ...} and the
	// trace is the union of every event that established any cell in it.
	QuerySubject(context.Context, *SubjectRequest) (*TracedAnswer, error)
	QueryGraph(context.Context, *Empty) (*ViewState, error)
	QuerySeries(context.Context, *SeriesRequest) (*ViewState, error)
	Why(context.Context, *WhyRequest) (*RecordList, error)
	Audit(context.Context, *AuditRequest) (*AuditFinding, error)
	Seal(context.Context, *Empty) (*Receipt, error)
	Rotate(context.Context, *Empty) (*RotateInfo, error)
	Backup(*BackupRequest, grpc.ServerStreamingServer[BackupChunk]) error
	Attest(context.Context, *Empty) (*Attestation, error)
	// Cluster plane (G8, PLAN4): Raft-style election + quorum-acked replication.
	// Only meaningful when KIVI_CLUSTER is set; single-node servers answer
	// FailedPrecondition.
	Vote(context.Context, *VoteRequest) (*VoteReply, error)
	Beat(context.Context, *BeatRequest) (*BeatReply, error)
	// The follower opens the stream to the LEADER: the leader pushes records,
	// the follower sends acks on the same stream. Acks drive the commit index.
	Replicate(grpc.BidiStreamingServer[ReplicateAck, RecordReply]) error
	// Federation (PLAN6): fetch a fresh attestation from a peer and FILE it in
	// this ledger as a kivi.witness event — mutual testimony without consensus.
	Witness(context.Context, *WitnessRequest) (*Receipt, error)
	// Semantic view (PLAN7): traced similarity search. Every hit is a record
	// number with its score and raw record; the reply names the model and the
	// covered scope — an untraced score does not exist.
	Similar(context.Context, *SimilarRequest) (*SimilarReply, error)
	// Identity plane (PLAN8): password login → session token (Bearer). User
	// management itself is receipted kivi.user events (admin plane / local CLI).
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// Head is the cheap orientation call: the ledger's last record number and
	// head hash, straight from the open writer — NO cryptographic audit runs.
	// Tail readers (recent_events, pagination) should use this, and reach for
	// Verify only when integrity itself is the question.
	Head(context.Context, *Empty) (*HeadReply, error)
	// Paged view reads: deterministic KEYSET pagination over a compiled view's
	// canonical (sorted) keys — no offsets, no drift. Snapshot pinning: page 1
	// answers with the scope it folded to; pass that scope back as as_of on
	// later pages and EVERY page describes the same moment (time travel reused
	// as pagination glue). Record streams page differently: Replay(from) — the
	// record number IS the cursor.
	QueryViewPage(context.Context, *ViewPageRequest) (*ViewPage, error)
	// Subscribe (G14): a TYPE-FILTERED live feed for point consumers that only
	// care about one or two event types (a worker fed only kivi.apikey, a
	// dashboard fed only kivi.metric) — the same live-tail mechanism as Replay,
	// but the server drops non-matching records before they cross the wire
	// instead of making every consumer receive and discard everything.
	//
	// Honesty note: filtering BY DESIGN creates gaps in the record numbering,
	// so this stream does NOT carry Replay's gapless/chain-adjacency promise —
	// each delivered record's OWN hash (and seal signature, for kivi.seal
	// records) is still independently verifiable, proving "byte-exact what the
	// ledger holds," but never "you received everything." A consumer that
	// needs the stronger, audit-grade guarantee (replicas, backup, CDC that
	// must prove no record was skipped) uses Replay — unfiltered — instead.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[RecordReply]) error
	// Graph traversal over `relation` events (traced, bounded, as-of). The server
	// folds relations into an adjacency and walks it; every answer carries the
	// record numbers of the edges it crossed. Reader role.
	GraphNeighbors(context.Context, *GraphNeighborsRequest) (*GraphEdges, error)
	GraphReachable(context.Context, *GraphReachableRequest) (*GraphReachableReply, error)
	GraphPath(context.Context, *GraphPathRequest) (*GraphPathReply, error)
	mustEmbedUnimplementedKiviServer()
}

// UnimplementedKiviServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKiviServer struct{}

func (UnimplementedKiviServer) Append(context.Context, *AppendRequest) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedKiviServer) AppendBatch(grpc.ClientStreamingServer[AppendRequest, ReceiptList]) error {
	return status.Error(codes.Unimplemented, "method AppendBatch not implemented")
}
func (UnimplementedKiviServer) AppendPrivate(context.Context, *AppendRequest) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendPrivate not implemented")
}
func (UnimplementedKiviServer) Erase(context.Context, *EraseRequest) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedKiviServer) GetRecord(context.Context, *GetRecordRequest) (*RecordReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedKiviServer) Replay(*ReplayRequest, grpc.ServerStreamingServer[RecordReply]) error {
	return status.Error(codes.Unimplemented, "method Replay not implemented")
}
func (UnimplementedKiviServer) Verify(context.Context, *Empty) (*VerifyReport, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedKiviServer) QueryTable(context.Context, *TableRequest) (*TracedAnswer, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTable not implemented")
}
func (UnimplementedKiviServer) QuerySubject(context.Context, *SubjectRequest) (*TracedAnswer, error) {
	return nil, status.Error(codes.Unimplemented, "method QuerySubject not implemented")
}
func (UnimplementedKiviServer) QueryGraph(context.Context, *Empty) (*ViewState, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryGraph not implemented")
}
func (UnimplementedKiviServer) QuerySeries(context.Context, *SeriesRequest) (*ViewState, error) {
	return nil, status.Error(codes.Unimplemented, "method QuerySeries not implemented")
}
func (UnimplementedKiviServer) Why(context.Context, *WhyRequest) (*RecordList, error) {
	return nil, status.Error(codes.Unimplemented, "method Why not implemented")
}
func (UnimplementedKiviServer) Audit(context.Context, *AuditRequest) (*AuditFinding, error) {
	return nil, status.Error(codes.Unimplemented, "method Audit not implemented")
}
func (UnimplementedKiviServer) Seal(context.Context, *Empty) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Seal not implemented")
}
func (UnimplementedKiviServer) Rotate(context.Context, *Empty) (*RotateInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Rotate not implemented")
}
func (UnimplementedKiviServer) Backup(*BackupRequest, grpc.ServerStreamingServer[BackupChunk]) error {
	return status.Error(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedKiviServer) Attest(context.Context, *Empty) (*Attestation, error) {
	return nil, status.Error(codes.Unimplemented, "method Attest not implemented")
}
func (UnimplementedKiviServer) Vote(context.Context, *VoteRequest) (*VoteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Vote not implemented")
}
func (UnimplementedKiviServer) Beat(context.Context, *BeatRequest) (*BeatReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Beat not implemented")
}
func (UnimplementedKiviServer) Replicate(grpc.BidiStreamingServer[ReplicateAck, RecordReply]) error {
	return status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedKiviServer) Witness(context.Context, *WitnessRequest) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Witness not implemented")
}
func (UnimplementedKiviServer) Similar(context.Context, *SimilarRequest) (*SimilarReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Similar not implemented")
}
func (UnimplementedKiviServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedKiviServer) Head(context.Context, *Empty) (*HeadReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Head not implemented")
}
func (UnimplementedKiviServer) QueryViewPage(context.Context, *ViewPageRequest) (*ViewPage, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryViewPage not implemented")
}
func (UnimplementedKiviServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[RecordReply]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedKiviServer) GraphNeighbors(context.Context, *GraphNeighborsRequest) (*GraphEdges, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphNeighbors not implemented")
}
func (UnimplementedKiviServer) GraphReachable(context.Context, *GraphReachableRequest) (*GraphReachableReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphReachable not implemented")
}
func (UnimplementedKiviServer) GraphPath(context.Context, *GraphPathRequest) (*GraphPathReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphPath not implemented")
}
func (UnimplementedKiviServer) mustEmbedUnimplementedKiviServer() {}
func (UnimplementedKiviServer) testEmbeddedByValue()              {}

// UnsafeKiviServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KiviServer will
// result in compilation errors.
type UnsafeKiviServer interface {
	mustEmbedUnimplementedKiviServer()
}

func RegisterKiviServer(s grpc.ServiceRegistrar, srv KiviServer) {
	// If the following call panics, it indicates UnimplementedKiviServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kivi_ServiceDesc, srv)
}

func _Kivi_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_AppendBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KiviServer).AppendBatch(&grpc.GenericServerStream[AppendRequest, ReceiptList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kivi_AppendBatchServer = grpc.ClientStreamingServer[AppendRequest, ReceiptList]

func _Kivi_AppendPrivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).AppendPrivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_AppendPrivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).AppendPrivate(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Erase(ctx, req.(*EraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_GetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Replay_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReplayRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KiviServer).Replay(m, &grpc.GenericServerStream[ReplayRequest, RecordReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kivi_ReplayServer = grpc.ServerStreamingServer[RecordReply]

func _Kivi_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Verify(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_QueryTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).QueryTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_QueryTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).QueryTable(ctx, req.(*TableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_QuerySubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).QuerySubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_QuerySubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).QuerySubject(ctx, req.(*SubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_QueryGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).QueryGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_QueryGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).QueryGraph(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_QuerySeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).QuerySeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_QuerySeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).QuerySeries(ctx, req.(*SeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Why_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Why(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Why_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Why(ctx, req.(*WhyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Audit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Audit(ctx, req.(*AuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Seal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Seal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Seal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Seal(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Rotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Rotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Rotate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Rotate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Backup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BackupRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KiviServer).Backup(m, &grpc.GenericServerStream[BackupRequest, BackupChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kivi_BackupServer = grpc.ServerStreamingServer[BackupChunk]

func _Kivi_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Attest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Attest(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Vote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Beat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Beat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Beat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Beat(ctx, req.(*BeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KiviServer).Replicate(&grpc.GenericServerStream[ReplicateAck, RecordReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kivi_ReplicateServer = grpc.BidiStreamingServer[ReplicateAck, RecordReply]

func _Kivi_Witness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WitnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Witness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Witness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Witness(ctx, req.(*WitnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Similar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Similar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Similar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Similar(ctx, req.(*SimilarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Head_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).Head(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_Head_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).Head(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_QueryViewPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).QueryViewPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_QueryViewPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).QueryViewPage(ctx, req.(*ViewPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KiviServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, RecordReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kivi_SubscribeServer = grpc.ServerStreamingServer[RecordReply]

func _Kivi_GraphNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).GraphNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_GraphNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).GraphNeighbors(ctx, req.(*GraphNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_GraphReachable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphReachableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).GraphReachable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_GraphReachable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).GraphReachable(ctx, req.(*GraphReachableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kivi_GraphPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiviServer).GraphPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kivi_GraphPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiviServer).GraphPath(ctx, req.(*GraphPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Kivi_ServiceDesc is the grpc.ServiceDesc for Kivi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kivi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kivi.v1.Kivi",
	HandlerType: (*KiviServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _Kivi_Append_Handler,
		},
		{
			MethodName: "AppendPrivate",
			Handler:    _Kivi_AppendPrivate_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _Kivi_Erase_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _Kivi_GetRecord_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Kivi_Verify_Handler,
		},
		{
			MethodName: "QueryTable",
			Handler:    _Kivi_QueryTable_Handler,
		},
		{
			MethodName: "QuerySubject",
			Handler:    _Kivi_QuerySubject_Handler,
		},
		{
			MethodName: "QueryGraph",
			Handler:    _Kivi_QueryGraph_Handler,
		},
		{
			MethodName: "QuerySeries",
			Handler:    _Kivi_QuerySeries_Handler,
		},
		{
			MethodName: "Why",
			Handler:    _Kivi_Why_Handler,
		},
		{
			MethodName: "Audit",
			Handler:    _Kivi_Audit_Handler,
		},
		{
			MethodName: "Seal",
			Handler:    _Kivi_Seal_Handler,
		},
		{
			MethodName: "Rotate",
			Handler:    _Kivi_Rotate_Handler,
		},
		{
			MethodName: "Attest",
			Handler:    _Kivi_Attest_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _Kivi_Vote_Handler,
		},
		{
			MethodName: "Beat",
			Handler:    _Kivi_Beat_Handler,
		},
		{
			MethodName: "Witness",
			Handler:    _Kivi_Witness_Handler,
		},
		{
			MethodName: "Similar",
			Handler:    _Kivi_Similar_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Kivi_Login_Handler,
		},
		{
			MethodName: "Head",
			Handler:    _Kivi_Head_Handler,
		},
		{
			MethodName: "QueryViewPage",
			Handler:    _Kivi_QueryViewPage_Handler,
		},
		{
			MethodName: "GraphNeighbors",
			Handler:    _Kivi_GraphNeighbors_Handler,
		},
		{
			MethodName: "GraphReachable",
			Handler:    _Kivi_GraphReachable_Handler,
		},
		{
			MethodName: "GraphPath",
			Handler:    _Kivi_GraphPath_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AppendBatch",
			Handler:       _Kivi_AppendBatch_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Replay",
			Handler:       _Kivi_Replay_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Backup",
			Handler:       _Kivi_Backup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Replicate",
			Handler:       _Kivi_Replicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _Kivi_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/kivi.proto",
}
